import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "next-themes";
import { SessionProvider } from "@/providers/session-provider";
import { PhosphorProvider } from "@/providers/phosphor-provider";
import { QueryProvider } from "@/providers/query-provider";
import { ApiAuthProvider } from "@/providers/api-auth-provider";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-background">
        <SessionProvider>
          <PhosphorProvider>
            <QueryProvider>
              <ApiAuthProvider>
                <SidebarProvider>
                  <AppSidebar />
                  <SidebarInset className="overflow-x-hidden">
                    {children}
                  </SidebarInset>
                </SidebarProvider>
                <Toaster />
              </ApiAuthProvider>
            </QueryProvider>
          </PhosphorProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
