import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PhosphorProvider } from "@/providers/phosphor-provider";
import { QueryProvider } from "@/providers/query-provider";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-background">
        <PhosphorProvider>
          <QueryProvider>
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset className="overflow-x-hidden">
                {children}
              </SidebarInset>
            </SidebarProvider>
          </QueryProvider>
        </PhosphorProvider>
      </body>
    </html>
  );
}
